run:
  timeout: 5m
  modules-download-mode: vendor

linters-settings:
  exhaustruct:
    include:
      - "\\..*Config"
  goimports:
    local-prefixes: "github.com/hedhyw/otelinji"
  cyclop:
    max-complexity: 15

linters:
  enable-all: true
  disable:
    - funlen
    - gci
    - wrapcheck
    - varnamelen
    - testpackage
    - exhaustive
    - gomoddirectives
    - nonamedreturns
    - bodyclose
    - wastedassign
    - tparallel
    - sqlclosecheck
    - rowserrcheck
    - noctx
    - nilerr
    - contextcheck
    - musttag
    - spancheck
    - depguard
    - exportloopref

issues:
  fix: true
  exclude-dirs:
  - "internal/infra/inframocks"
  exclude-rules:
    - linters:
        - thelper
      source: "^.*f\\.Scenario.*$"
    - linters:
        - goerr113
      path: "^.+_test.go$"