version: "2"
linters:
  default: all
  disable:
    - bodyclose
    - contextcheck
    - depguard
    - exhaustive
    - funlen
    - gomoddirectives
    - musttag
    - nilerr
    - noctx
    - noinlineerr
    - nonamedreturns
    - rowserrcheck
    - spancheck
    - sqlclosecheck
    - testpackage
    - tparallel
    - varnamelen
    - wastedassign
    - wrapcheck
  settings:
    cyclop:
      max-complexity: 15
    exhaustruct:
      include:
        - \..*Config
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - thelper
        source: ^.*f\.Scenario.*$
      - linters:
          - err113
          - goconst
        path: ^.+_test.go$
    paths:
      - internal/infra/inframocks
      - third_party$
      - builtin$
      - examples$
issues:
  fix: true
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/hedhyw/otelinji
  exclusions:
    generated: lax
    paths:
      - internal/infra/inframocks
      - third_party$
      - builtin$
      - examples$
