run:
  timeout: 5m
  modules-download-mode: vendor
  skip-dirs:
    - "internal/infra/inframocks"

linters-settings:
  exhaustruct:
    include:
      - "\\..*Config"
  goimports:
    local-prefixes: "github.com/hedhyw/otelinj"

linters:
  enable-all: true
  disable:
    - funlen
    - maligned
    - exhaustivestruct
    - gci
    - wrapcheck
    - varnamelen
    - testpackage
    - exhaustive
    - gomnd
    - interfacer
    - scopelint
    - golint
    - gomoddirectives
    - nonamedreturns
    # go1.18
    - bodyclose
    - wastedassign
    - tparallel
    - structcheck
    - sqlclosecheck
    - rowserrcheck
    - noctx
    - nilerr
    - contextcheck

issues:
  fix: true
  exclude-rules:
    - linters:
        - thelper
      source: "^.*f\\.Scenario.*$"
    - linters:
        - goerr113
      path: "^.+_test.go$"