name: check-otelinji

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.4"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.14.0

      - name: Lint
        run: task check

      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.out
